### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by wolftic** [MrElektronix/2DZombieScroller#10]
Denk aan je tabjes voor leesbaarheid of denk aan het gebruiken van een code formatter

https://github.com/MrElektronix/2DZombieScroller/blob/62e381195d78efe8b2b30639434e1d8302583326/2DZombieScroller/Assets/Scripts/Player.cs#L18-L28

**Comment by burritosss** [comment]
+1

**Comment by MrElektronix** [comment]
fixed

**Comment by MrElektronix** [comment]
fixed tabjes
