### ISSUE TITLE
Awake ipv Start

### ISSUE THREAD

**Issue by wolftic** [MrElektronix/2DZombieScroller#11]
Meestal is het beter om variables te setten in de Awake.
Oftewel GetComponent in Awake etc.

https://github.com/MrElektronix/2DZombieScroller/blob/62e381195d78efe8b2b30639434e1d8302583326/2DZombieScroller/Assets/Scripts/Player.cs#L10

**Comment by burritosss** [comment]
+1 vars setten in awake en gebruiken in start

**Comment by MrElektronix** [comment]
Replaced Start with Awake function where needed
