### ISSUE TITLE
Aparte functie

### ISSUE THREAD

**Issue by wolftic** [MrElektronix/2DZombieScroller#12]
Probeer voor het spawnen van een enemy een aparte functie te maken waar je bijvoorbeeld de locatie meegeeft zodat je die functionaliteit evt kan hergebruiken.

enemies+= 1 is het zelfde als enemies++

https://github.com/MrElektronix/2DZombieScroller/blob/62e381195d78efe8b2b30639434e1d8302583326/2DZombieScroller/Assets/Scripts/EnemySpawner.cs#L23-L25

**Comment by burritosss** [comment]
+1

**Comment by MrElektronix** [comment]
Made a seperate function for the enemies:

private void CreateEnemy(int spawnpoint){
Instantiate(_enemyObject,_spawnPoints[spawnpoint].transform.position,_spawnPoints[spawnpoint].transform.rotation);
}
