### ISSUE TITLE
attributes

### ISSUE THREAD

**Issue by wolftic** [MrElektronix/2DZombieScroller#13]
Probeer zoveel mogelijk je attributen boven je variables te doen

aka
[SerializeField]
private blala

https://github.com/MrElektronix/2DZombieScroller/blob/62e381195d78efe8b2b30639434e1d8302583326/2DZombieScroller/Assets/Scripts/CameraFollow.cs#L6

**Comment by burritosss** [comment]
-1 personal pref

**Comment by MrElektronix** [comment]
-1 personal preference
