### ISSUE TITLE
why

### ISSUE THREAD

**Issue by wolftic** [MrElektronix/2DZombieScroller#14]
Virtual Update? Why?
Update werkt in elk script dat uiteindelijk overerft van MonoBehaviour

https://github.com/MrElektronix/2DZombieScroller/blob/62e381195d78efe8b2b30639434e1d8302583326/2DZombieScroller/Assets/Scripts/CharacterBase.cs#L28-L30

**Comment by burritosss** [comment]
+1

**Comment by MrElektronix** [comment]
removed virtual from update functions
