### ISSUE TITLE
Abstract ipv Virtual als je geen logica erin hebt

### ISSUE THREAD

**Issue by wolftic** [MrElektronix/2DZombieScroller#15]
Als je weet dat de classes die deze class overerfen Move gaan gebruiken en je geen functionaliteit in je main class hebt daarvoor. Probeer dan ipv virtual abstract te gebruiken.

public abstract void Move();

https://github.com/MrElektronix/2DZombieScroller/blob/62e381195d78efe8b2b30639434e1d8302583326/2DZombieScroller/Assets/Scripts/CharacterBase.cs#L24-L26

**Comment by burritosss** [comment]
+1

**Comment by MrElektronix** [comment]
public virtual void Move(){
		//transform.Translate(new Vector3(Speed, 0f, 0f) * Time.deltaTime);
}

vervangen met een abstracte functie: public abstract void Move();
