### ISSUE TITLE
Minor performance

### ISSUE THREAD

**Issue by wolftic** [MrElektronix/2DZombieScroller#9]
Je maakt nu elke paar seconde een nieuw object met dezelfde tijd, terwijl je ook 1x het object kan maken en kan hergebruiken. Dit scheelt performance

https://github.com/MrElektronix/2DZombieScroller/blob/62e381195d78efe8b2b30639434e1d8302583326/2DZombieScroller/Assets/Scripts/EnemySpawner.cs#L21

**Comment by burritosss** [comment]
+1

**Comment by MrElektronix** [comment]
fixed

**Comment by burritosss** [comment]
show ook waar en hoe pls

**Comment by MrElektronix** [comment]
Changed: private IEnumerator Spawn(float time){
		     while (_currentEnemyCount != _maxEnemyCount){
		        yield return new WaitForSeconds(time);

To:  private IEnumerator Spawn(float time){
         WaitForSeconds cooldown = new WaitForSeconds(time);
         while (_currentEnemyCount != _maxEnemyCount){
		        yield return cooldown;

Is this version the object with the time gets created once instead of created everytime the spawn function is called
